---

# This should possibly be a module that just check whether python 2.7 is there before doing anything

- name : install build-essential
  apt:
    name: build-essential

- name: Download Python27 source
  get_url: url=http://python.org/ftp/python/2.7.6/Python-2.7.6.tgz dest=/tmp/Python-2.7.6.tgz owner=root group=root force=no
  become: true

- name: Extract Python27 source
  command: /bin/tar -xzf /tmp/Python-2.7.6.tgz chdir=/usr/local/src creates=/usr/local/src/Python-2.7.6/configure
  become: true

- name: Make and *ALT* install Python27
  shell: ./configure --prefix=/usr/local --enable-shared && /usr/bin/make && /usr/bin/make altinstall chdir=/usr/local/src/Python-2.7.6/ creates=/usr/local/bin/python2.7
  become: true

- name: easy_install
  apt:
    name: python-setuptools
    state: present
  become: true

- name: install dependencies
  apt:
    name: ["python-psycopg2", "libpq-dev"]
    state: present
  become: true

- name: pip + virtualenv
  easy_install:
    name: "{{ item }}"
  with_items:
    - "pip"
    - "py2-ipaddress"
 #  - "virtualenv"
  become: true

- name: install virtualenv
  pip:
    name: virtualenv

- name: Symlink python27
  file: src=/usr/local/bin/python2.7 dest=/usr/local/bin/python27 state=link
  become: true

- name: Install postgresql
  apt:
    name: postgresql
    state: present
  become: true
  become_user: root

- name: Create postgresql User
  community.general.postgresql_user:
    name: odoo
    password: odoo
    role_attr_flags: CREATEDB,CREATEROLE
  become: true
  become_user: postgres

- name: Modify pg_hba
  community.general.postgresql_pg_hba:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    address: "{{ item }}"
    contype: host
    users: all
    databases: all
  with_items:
    - "10.184.0.0/20"
    - "10.148.0.0/20"
  become: true
  become_user: root
  notify:
     - reload postgresql
  #- name: Add host to allow db connection
  #lineinfile:
  #  path: /etc/postgresql/9.5/main/pg_hba.conf
  #  line: "{{ item.line }}"
  #with_items:
  #  - { host    all             all             10.184.0.0/20           md5 }
  #  - { host    all             all             10.148.0.0/20           md5 }


- name: Change Postgresql Listen Address
  lineinfile:
    path: /etc/postgresql/9.5/main/postgresql.conf
  #  regexp: #listen_addresses = 'localhost'
  #  insertbefore: #listen_addresses = 'localhost'
    line: listen_addresses = '*'
  notify:
    - restart postgresql
